/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voting;

import Stud_Dashboard.Stud_Dashboard;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class vote_n extends javax.swing.JFrame {

    /**
     * Creates new form vote_n
     */
    
    
    
    public vote_n() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_pLuf = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_pGok = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_vpZoro = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_vpVeg = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btn_secSan = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btn_secTru = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn_treNami = new javax.swing.JButton();
        btn_treHan = new javax.swing.JButton();
        btn_audRob = new javax.swing.JButton();
        btn_audSat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_count = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 59, 118));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VOTING SECTION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic_candidates/luffy.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" President");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        btn_pLuf.setText("Vote");
        btn_pLuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pLufActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pLuf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 60, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic_candidates/goku.png"))); // NOI18N
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 100, 100));

        btn_pGok.setText("Vote");
        btn_pGok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pGokActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pGok, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 60, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic_candidates/zoro.png"))); // NOI18N
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 100, 100));

        btn_vpZoro.setText("Vote");
        btn_vpZoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vpZoroActionPerformed(evt);
            }
        });
        jPanel1.add(btn_vpZoro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 60, -1));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic_candidates/vegeta.png"))); // NOI18N
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 100, 100));

        btn_vpVeg.setText("Vote");
        btn_vpVeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vpVegActionPerformed(evt);
            }
        });
        jPanel1.add(btn_vpVeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 60, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Vice President");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic_candidates/sanji.png"))); // NOI18N
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 100, 100));

        btn_secSan.setText("Vote");
        btn_secSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_secSanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_secSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 60, -1));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic_candidates/trunks.png"))); // NOI18N
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 100, 100));

        btn_secTru.setText("Vote");
        btn_secTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_secTruActionPerformed(evt);
            }
        });
        jPanel1.add(btn_secTru, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 60, -1));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic_candidates/Nami.png"))); // NOI18N
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 100, 100));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic_candidates/tenshin.png"))); // NOI18N
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 100, 100));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic_candidates/robin.png"))); // NOI18N
        jPanel13.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 100, 100));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic_candidates/videl.png"))); // NOI18N
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 100, 100));

        btn_treNami.setText("Vote");
        btn_treNami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_treNamiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_treNami, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 60, -1));

        btn_treHan.setText("Vote");
        btn_treHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_treHanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_treHan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 60, -1));

        btn_audRob.setText("Vote");
        btn_audRob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_audRobActionPerformed(evt);
            }
        });
        jPanel1.add(btn_audRob, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 60, -1));

        btn_audSat.setText("Vote");
        btn_audSat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_audSatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_audSat, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 60, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Secretary");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Treasurer");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Auditor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, -1));

        jButton11.setBackground(new java.awt.Color(17, 128, 14));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton11.setText("SUBMIT VOTES");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, -1, 30));

        jButton12.setBackground(new java.awt.Color(196, 39, 58));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, 90, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(txt_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 590));

        setSize(new java.awt.Dimension(882, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        this.setVisible(false);
        new Stud_Dashboard().setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private int voteCount = 0;
    private boolean hasVoted = false;

    private StringBuilder buttonPresses = new StringBuilder();

    private void logButtonPress(String buttonName) {
        buttonPresses.append(buttonName).append("|");
    }


    private void btn_pLufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pLufActionPerformed
        if (!hasVoted) {
            JOptionPane.showMessageDialog(null, "Vote successfully recorded");
            btn_pLuf.setEnabled(false); // Disabling this button after the user has voted once
            btn_pGok.setEnabled(false);
            voteCount++;
            logButtonPress("President Luffy");
        } else {
            JOptionPane.showMessageDialog(null, "You have already voted once.");
        }
    }//GEN-LAST:event_btn_pLufActionPerformed

    private void btn_pGokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pGokActionPerformed
        if (!hasVoted) {
            JOptionPane.showMessageDialog(null, "Vote successfully recorded");
            btn_pLuf.setEnabled(false); // Disabling this button after the user has voted once
            btn_pGok.setEnabled(false);
            voteCount++;
            logButtonPress("President Goku");
        } else {
            JOptionPane.showMessageDialog(null, "You have already voted once.");
        }
    }//GEN-LAST:event_btn_pGokActionPerformed

    private void btn_vpZoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vpZoroActionPerformed
        if (!hasVoted) {
            JOptionPane.showMessageDialog(null, "Vote successfully recorded");
            btn_vpZoro.setEnabled(false); 
            btn_vpVeg.setEnabled(false);
            voteCount++;
            logButtonPress("Vice President Zoro");
        } else {
            JOptionPane.showMessageDialog(null, "You have already voted once.");
        }
    }//GEN-LAST:event_btn_vpZoroActionPerformed

    private void btn_vpVegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vpVegActionPerformed
        if (!hasVoted) {
            JOptionPane.showMessageDialog(null, "Vote successfully recorded");
            btn_vpZoro.setEnabled(false); 
            btn_vpVeg.setEnabled(false);
            voteCount++;
            logButtonPress("Vice President Vegita");
        } else {
            JOptionPane.showMessageDialog(null, "You have already voted once.");
        }
    }//GEN-LAST:event_btn_vpVegActionPerformed

    private void btn_secSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_secSanActionPerformed
        if (!hasVoted) {
            JOptionPane.showMessageDialog(null, "Vote successfully recorded");
            btn_secSan.setEnabled(false);
            btn_secTru.setEnabled(false);
            voteCount++;
            logButtonPress("Secretary Sanji");
        } else {
            JOptionPane.showMessageDialog(null, "You have already voted once.");
        }
    }//GEN-LAST:event_btn_secSanActionPerformed

    private void btn_secTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_secTruActionPerformed
        if (!hasVoted) {
            JOptionPane.showMessageDialog(null, "Vote successfully recorded");
            btn_secSan.setEnabled(false);
            btn_secTru.setEnabled(false);
            voteCount++;
            logButtonPress("Secretary Trunks");
        } else {
            JOptionPane.showMessageDialog(null, "You have already voted once.");
        }
    }//GEN-LAST:event_btn_secTruActionPerformed

    private void btn_treNamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_treNamiActionPerformed
        if (!hasVoted) {
            JOptionPane.showMessageDialog(null, "Vote successfully recorded");
            btn_treHan.setEnabled(false);
            btn_treNami.setEnabled(false);
            voteCount++;
            logButtonPress("Treasurer Nami");
        } else {
            JOptionPane.showMessageDialog(null, "You have already voted once.");
        }
    }//GEN-LAST:event_btn_treNamiActionPerformed

    private void btn_treHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_treHanActionPerformed
        if (!hasVoted) {
            JOptionPane.showMessageDialog(null, "Vote successfully recorded");
            btn_treHan.setEnabled(false);
            btn_treNami.setEnabled(false);
            voteCount++;
            logButtonPress("Treasurer Shinhan");
        } else {
            JOptionPane.showMessageDialog(null, "You have already voted once.");
        }
    }//GEN-LAST:event_btn_treHanActionPerformed

    private void btn_audRobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_audRobActionPerformed
        if (!hasVoted) {
            JOptionPane.showMessageDialog(null, "Vote successfully recorded");
            btn_audSat.setEnabled(false);
            btn_audRob.setEnabled(false);
            voteCount++;
            logButtonPress("Auditor Robin");
        } else {
            JOptionPane.showMessageDialog(null, "You have already voted once.");
    }
    }//GEN-LAST:event_btn_audRobActionPerformed

    private void btn_audSatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_audSatActionPerformed
        if (!hasVoted) {
            JOptionPane.showMessageDialog(null, "Vote successfully recorded");
            btn_audSat.setEnabled(false);
            btn_audRob.setEnabled(false);
            voteCount++;
            logButtonPress("Auditor Satan");
        } else {
            JOptionPane.showMessageDialog(null, "You have already voted once.");
        }
    }//GEN-LAST:event_btn_audSatActionPerformed

    
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
        if (voteCount >= 5) {
            String directoryPath = "users";

            // Create the directory if it doesn't exist
            File directory = new File(directoryPath);
            if (!directory.exists()) {
                directory.mkdirs();
            }

            // File path
            String filePath = directoryPath + File.separator + "vote_result.txt";

            try {
                // Create or append to the file
                FileWriter writer = new FileWriter(filePath, true);

                // Append button presses
                writer.write("Button presses: " + buttonPresses.toString() + "\n");

                // Close the writer
                writer.close();

                // Show success message
                JOptionPane.showMessageDialog(null, "Submitted successfully");
                updateVoteCount();
            } catch (IOException e) {
                System.out.println("An error occurred.");
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please vote in all fields before submitting.");
        }
    }
                                       
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vote_n.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vote_n.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vote_n.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vote_n.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vote_n().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_audRob;
    private javax.swing.JButton btn_audSat;
    private javax.swing.JButton btn_pGok;
    private javax.swing.JButton btn_pLuf;
    private javax.swing.JButton btn_secSan;
    private javax.swing.JButton btn_secTru;
    private javax.swing.JButton btn_treHan;
    private javax.swing.JButton btn_treNami;
    private javax.swing.JButton btn_vpVeg;
    private javax.swing.JButton btn_vpZoro;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel txt_count;
    // End of variables declaration//GEN-END:variables

    private void updateVoteCount() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
